### ISSUE TITLE
Android version not supported

### ISSUE THREAD

**Issue by kundank191** [UdacityAndroidDevScholarship/blood-donation#13]
In splashScreenActivity.java , lines 66 , 82 , 99 , function `mAppVersionView.getViewTreeObserver().removeOnGlobalLayoutListener(this);` , this requires api level 16 , app has min api level 15.

**Comment by sakchhams** [comment]
@kundank191 update your issue to match the [template](https://github.com/UdacityAndroidDevScholarship/blood-donation/blob/master/.github/ISSUE_TEMPLATE.md). It is made to ensure uniformity across the project. Please stick to the same.

**Comment by kundank191** [comment]
Environment
Version : 
Bug:
It was a warning that the fucntion can oly be used for API level 16 and above.
When does this occur?
Steps to reproduce:
1. navigate to app
2. navigate to java
3. navigate to com.udacity.nanodegree.blooddonation
4. navigate to ui
5. navigate to splash
6. open splash screen activity
7. goto lines 66, 82 , 99
IDE shows warning that the function requires minimum api 16
Solution : 
set minimum api level 16.

**Comment by sakchhams** [comment]
@kundank191 closed the issue? Edit the original post to match the same and delete the above.
