### ISSUE TITLE
Add Animations to Splash Screen.

### ISSUE THREAD

**Issue by shachiShah** [UdacityAndroidDevScholarship/blood-donation#14]
Splash screen needs animations.

Currently, the splash screen is simple. Animating it will make it more catchy and attractive.
The main app_logo and the app_name are flashed from the screen before the home page.

**Comment by sakchhams** [comment]
@shachiShah update issue to match the [template](https://github.com/UdacityAndroidDevScholarship/blood-donation/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by ritesh-singh** [comment]
I guess still the logo and splash screen are getting finialised.
There is no deadline as of now

**Comment by shachiShah** [comment]
Are the logo and app name finalized?
