### ISSUE TITLE
Develop signup screen (signup(A)) as per mock pdf

### ISSUE THREAD

**Issue by ritesh-singh** [UdacityAndroidDevScholarship/blood-donation#15]
Create Registration UI for signup page 1, don't include phone number as given in mock.

**Comment by intkhabahmed** [comment]
Assign to me.

**Comment by sakchhams** [comment]
@ritesh-singh assign issue using standard GitHub assignment. Please don't change the title, also could you please make the issue description a little more explanatory. Fill out the [template](https://github.com/UdacityAndroidDevScholarship/blood-donation/blob/master/.github/ISSUE_TEMPLATE.md) for starters.

**Comment by ritesh-singh** [comment]
@sakchhams okay, well, @intkhabahmed had commented above. He name doesnt show up in the assignees list.

**Comment by ritesh-singh** [comment]
@shaech - Take mock pdf as a reference. It's signup(A) screen.
Drop, phone number from the field, just email and password.

Create a xml file and design the same.

**Comment by DIvu22** [comment]
I can design that screen as per the mockup

**Comment by shachiShah** [comment]
okk... @ritesh-singh

**Comment by ritesh-singh** [comment]
Have we made any progress yet?

**Comment by ritesh-singh** [comment]
Not, required. As per now flow.
