### ISSUE TITLE
Design user details screen

### ISSUE THREAD

**Issue by ritesh-singh** [UdacityAndroidDevScholarship/blood-donation#16]
Follow the registration mock
Signup(c) screen and add phone number as well here along with others.

**Comment by sakchhams** [comment]
@ritesh-singh assign issue using standard GitHub assignment. Please don't change the title, also could you please make the issue description a little more explanatory. Fill out the [template](https://github.com/UdacityAndroidDevScholarship/blood-donation/blob/master/.github/ISSUE_TEMPLATE.md) for starters.

**Comment by ritesh-singh** [comment]
Sure, can you try assigning it. I couldn't find in the assigness list.

**Comment by sakchhams** [comment]
@ritesh-singh anyone interested in working can comment here. They will show in the assignee list.

**Comment by intkhabahmed** [comment]
I will be working in this as ritesh said

**Comment by RathodKinjal76** [comment]
I want to work on this .

**Comment by intkhabahmed** [comment]
@RathodKinjal76 it's assigned to me

**Comment by ritesh-singh** [comment]
@intkhabahmed  

Take mock pdf as a reference. It's signup(C) screen.
Include phone number as an extra field here, as shown in signup(A) screen.

Create a xml file and design the same.

**Comment by intkhabahmed** [comment]
Ok @ritesh-singh

**Comment by ritesh-singh** [comment]
Have we made any progress yet?

**Comment by ritesh-singh** [comment]
Cool, even if you can push the basic layout also, will do. So, that i can write the singup flow and binding stuff. 
Anyways, take your time.

**Comment by intkhabahmed** [comment]
@ritesh-singh can you give the color codes used in the mockups

**Comment by surya07081995** [comment]
Hi @ritesh-singh, hope you are doing good.
I can design this UI.
Can you please  provide the sketch of the UI, so that  I can desgin as per your requirement.

**Comment by ritesh-singh** [comment]
@surya07081995 Checkout the channel for the wifreframe.
This is one is done by @intkhabahmed
