### ISSUE TITLE
Splash Screen Problem

### ISSUE THREAD

**Issue by saxenanihal95** [UdacityAndroidDevScholarship/blood-donation#25]
### Environment
  * Version : current version
  * Device/Operating System : All Devices
  
### Bug:
  * Pressing Back Button from main Screen shows Splash Screen
  * Required behavior is it should close the app when when back is pressed from main screen

#### Steps to reproduce:

  1. In  AndroidManifest.xml file, add `android:noHistory="true"` attribute in splash screen `<activity>`.

**Comment by sakchhams** [comment]
@saxenanihal95 thank you for the bug report. It's working completely fine as per my findings. Are you sure you're on the latest copy of the development branch? I'm closing this issue. Let me know if you find anything more.
