### ISSUE TITLE
Bad MVP implementation in UserRegistrationActivity

### ISSUE THREAD

**Issue by sakchhams** [UdacityAndroidDevScholarship/blood-donation#29]
### Environment
  * Version : develop 7bb6bd3e9b48d502584e714e9015ba2b4c9b3c39
  
### Bug:

  * What error did you encounter?
The Activity (`View`) implements signup logic which should be contained in the `Model`
  * When does this occur? 

  * What should be the behavior from your point of view? How do you expect the service to work?
Sign up logic should be implemented in the `Model`

### How would the above feature be useful?
Enforce MVP architecture to ensure uniformity across the project.

**Comment by ritesh-singh** [comment]
Signup logic cannot be containe in presenter, as it needs activity reference.

**Comment by ritesh-singh** [comment]
Can u suggest a better way???

**Comment by sakchhams** [comment]
@ritesh-singh it does not need an activity reference [see](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/PhoneAuthProvider)

**Comment by ritesh-singh** [comment]
@sakchhams It needs when you call verifyPhoneNumber, however, you use executor.

**Comment by ritesh-singh** [comment]
https://github.com/UdacityAndroidDevScholarship/blood-donation/pull/31

**Comment by ritesh-singh** [comment]
#31

**Comment by ritesh-singh** [comment]
Fixed!!
