### ISSUE TITLE
Improvements in UserRegistrationActivity

### ISSUE THREAD

**Issue by ShivamArora** [UdacityAndroidDevScholarship/blood-donation#32]
### Environment
  * Version : develop [7bb6bd3](https://github.com/ShivamArora/blood-donation/commit/7bb6bd3e9b48d502584e714e9015ba2b4c9b3c39)
  * Device/Operating System : Windows
  
### Bug:

  * What error did you encounter? Attaching screenshots or logs is always helpful.
     _The layouts relating to entering phone number and verify OTP are not up to the marks as per the mockups._ 

  * What should be the behaviour from your point of view? How do you expect the service to work?
   _The views need to be centered as per the mockups._

### Description
 - Ability to **resend the OTP code**.

### How would the above feature be useful?
 - This would allow the user to resend the OTP code to his phone number in case he doesn't receive one because of network issues.

### Technical Insights
 - How do you think it should be implemented.
   Add a **Resend Code** button within the OTP Verifier screen and resend the code using Firebase.

**Comment by ShivamArora** [comment]
@ritesh-singh @sakchhams I would like to work on this issue. Assign this to me.

**Comment by tavishjain** [comment]
@ritesh-singh @ShivamArora I faced a bug in the verify OTP screen. When I opened the app and registered first time , the Verify OTP screen opened. I hadn't even enter the OTP, it took me to the HomeActivity. Also , if I delete the user and create the user again, it is not verifying the user .

**Comment by ritesh-singh** [comment]
Yes, checkout the firebase phone auth documentation, sometimes it reads the OTP message directly and auhthenticate the user. But, not supported across all device. 
I haven't taken care of all use cases, as I am working on one full working flow.

However, we will have logout func and any feature you guys think is not proper, raise a bug for the same.

**Comment by ShivamArora** [comment]
@tavishjain Firebase PhoneAuth can automatically read the sms and thus the otp within it to verify. That's why it took you to  homescreen without you entering the otp.

@ritesh-singh @sakchhams Can I start working on this issue? Waiting for this issue to be assigned.

**Comment by tavishjain** [comment]
@ShivamArora for it to read the message, I should first recive the message. The issue is I have not even recieved the message and it is taking me to the HomeActivity

**Comment by ritesh-singh** [comment]
@tavishjain

**Comment by ShivamArora** [comment]
@ritesh-singh Yes. Would be working on it now + some improvements (centering the layouts) as per the mockups.

**Comment by ritesh-singh** [comment]
#43
