### ISSUE TITLE
Memory leak in UserLoginActivity

### ISSUE THREAD

**Issue by ritesh-singh** [UdacityAndroidDevScholarship/blood-donation#33]
# Template meant to be filled out when filing new issues

### Before Reporting
 - Check if the issue has already been reported on the [issue tracker](https://github.com/UdacityAndroidDevScholarship/blood-donation/issues)
 - Ensure you've successfully tested with the latest code.
 
### Environment
  * Version : _____
  * Device/Operating System : _____
  
### Bug:

  * What error did you encounter? Attaching screenshots or logs is always helpful.
  * When does this occur? 

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  ...
  
  * What should be the behaviour from your point of view? How do you expect the service to work?

### Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.
 
### Description
 - Describe the feature you want to add to the application.

### How would the above feature be useful?
 - Explain how your feature would make the application better.

### Technical Insights
 - How do you think it should be implemented.

**Comment by intkhabahmed** [comment]
@ritesh-singh Are you working on this?

**Comment by ritesh-singh** [comment]
@intkhabahmed I havent looked at it yet, sometimes leak canary shows, login activity is leaking.
Even after sigin, once i finish the login activity, GC is not able to collect it. Something is holding the activity reference.

You, can look at it, if you want.

**Comment by intkhabahmed** [comment]
ok I am working on it

**Comment by ritesh-singh** [comment]
Any luck?

**Comment by intkhabahmed** [comment]
No @ritesh-singh, I tried many things but still not solved, will try again afterwards..

**Comment by ritesh-singh** [comment]
Cool. This is open for anyone who wants to try.

**Comment by ShivamArora** [comment]
![screenshot_2018-04-16-19-42-18-080_com udacity nanodegree blooddonation](https://user-images.githubusercontent.com/4353659/38825853-99eafcdc-41cb-11e8-915c-c488bc34de4f.png)
This is what I see within the Leaks app.

**Comment by erzohrakhan** [comment]
Can I work on it?

**Comment by ritesh-singh** [comment]
@erzohrakhan sure.

**Comment by Bloody-Badboy** [comment]
Did you tried wrapping `UserLoginContract.View` in Presenter Impl class with `WeakReference<>`?

**Comment by ritesh-singh** [comment]
Yeah, this is the last solution. I couldn't find the cause though, it's phone auth api is holding the reference.

Thanks though!!

**Comment by ritesh-singh** [comment]
#69
