### ISSUE TITLE
User Details Screen

### ISSUE THREAD

**Issue by ritesh-singh** [UdacityAndroidDevScholarship/blood-donation#38]
Design and develop user details screen as per given in the mock.

On click of create button authenticated users information should be added in the firebase db.

**Comment by Hrishi1999** [comment]
Need more insight on this. Details.

**Comment by ritesh-singh** [comment]
#45

**Comment by intkhabahmed** [comment]
@ritesh-singh why did you remove the constraint layout and changed the button styles, it's not looking good

**Comment by ritesh-singh** [comment]
UI will be changed. Button styles I wanted to replicate the same. But didn't have much time, will add the same layout like u did.

There were few mistakes in the layout, as text view was inside radio group.
Date of birth view wasn't opening a calendar and others. And, I don't have much experience with constraint layout, so this was the better choice at that time.

You, can go ahead and add styles if you want or else i will do in a day or 2.

**Comment by intkhabahmed** [comment]
I have edited the layout and added back the constraint layout, will add the pull request tomorrow

**Comment by ritesh-singh** [comment]
Great, have you check functionality, and data binding.
Is data getting saved proper in db?

**Comment by intkhabahmed** [comment]
Yes I have checked, the data os getting inserted properly, just need to do local validations before pushing

**Comment by ritesh-singh** [comment]
okay.

**Comment by ritesh-singh** [comment]
#55
