### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by harikautilya** [UdacityAndroidDevScholarship/blood-donation#40]
[Time to work on Backbone - Final Mock I .pdf](https://github.com/UdacityAndroidDevScholarship/blood-donation/files/1914799/Time.to.work.on.Backbone.-.Final.Mock.I.pdf)

Will be working on this UI completely

**Comment by ritesh-singh** [comment]
Yes, userdetail and login screen is done.
There are few stuffs, which are left, like validation and UI.

Let's discuss the db structure first.

**Comment by harikautilya** [comment]
Sure let me know when you are free.

**Comment by Kautilyahari** [comment]
Starting coding pulling from the latest development branch.
