### ISSUE TITLE
Validation checks for user details screen

### ISSUE THREAD

**Issue by ritesh-singh** [UdacityAndroidDevScholarship/blood-donation#47]
User details screen have widgets like blood grp, name, lastname, gender, email and all.

There should be proper validation for all and since all fields are mandatory, user should not be able to proceed after clicking on createNow button.

A proper toast or snackbar message or toast should be shown.

**Comment by sud8443** [comment]
@ritesh-singh can I work on this issue?

**Comment by Hrishi1999** [comment]
@ritesh-singh I am working on it.

**Comment by ritesh-singh** [comment]
Anyone working on this?

**Comment by ritesh-singh** [comment]
Please, go ahead.

**Comment by Hrishi1999** [comment]
Has no work been done for Login UI? I am supposed to do the validation part
Should I make the UI too?

**Comment by Hrishi1999** [comment]
Currently, I am working on this. Just had some doubts.
