### ISSUE TITLE
Improve login screen design.

### ISSUE THREAD

**Issue by ritesh-singh** [UdacityAndroidDevScholarship/blood-donation#49]

**Comment by nishank95** [comment]
Can I work on it?

**Comment by xsahil03x** [comment]
![login 4](https://user-images.githubusercontent.com/25670178/38963718-f3060e08-4390-11e8-8124-8fc50619cdcf.png)

I can work on this 😄

**Comment by Hrishi1999** [comment]
I don't think this design looks good. Gradient seems old styled, not a fan of logo, maybe gradient buttons.

**Comment by AjaySharvesh3** [comment]
Shall I work on this?

**Comment by ritesh-singh** [comment]
@KamalMrock  is it done?

**Comment by KamalMrock** [comment]
@ritesh-singh if anybody would like to enhance the Login and OTP UI.
They can.

**Comment by ritesh-singh** [comment]
ok

**Comment by vibhuti16** [comment]
should we wait for the splash before proceeding to work on this?

**Comment by Hrishi1999** [comment]
I think we should continue working on different fragments, we will connect
them later.

**Comment by KamalMrock** [comment]
No need to wait for the splash screen.You guys can start your work.

**Comment by vibhuti16** [comment]
![login_blood_donation](https://user-images.githubusercontent.com/4936653/39519051-d8781bca-4e22-11e8-9f60-a78b07ca3d28.png)
a rough design made in paint

**Comment by xsahil03x** [comment]
Hey @vibhuti16 don't crop those buttons.  If you want those backgrounds then I can send you. 😀

**Comment by vibhuti16** [comment]
ya please do. but did youll like the design. can i work on this login screen?

**Comment by Pradhan10** [comment]
![img_20180503_193231_520](https://user-images.githubusercontent.com/16478419/39581367-085659e2-4f09-11e8-8af2-cfba51344f61.jpg)
![img_20180503_193252_086](https://user-images.githubusercontent.com/16478419/39581368-0893c016-4f09-11e8-928a-0b84bba33a67.jpg)
Changing button style. @vibhuti16 Please download file from here : https://drive.google.com/file/d/14myzKQ1QHc8WC7RBV33SE_ISKH18n_Ad/view?usp=sharing

**Comment by vibhuti16** [comment]
@KamalMrock have you developed this screen already?

**Comment by KamalMrock** [comment]
@vibhuti16 yes this part is done. #91
