### ISSUE TITLE
MVVM

### ISSUE THREAD

**Issue by rutulkotak** [UdacityAndroidDevScholarship/blood-donation#58]
## Bug Report
The project is following MVP:
-> MVP produce more classes and Java code
-> View delegates user input to Presenter; both of layers should have a 1 to 1 relation
-> Presenters are hard bound to view and not reusable

Where in MVVM:
-> We get officially recommended tools straight from Google, so we can worry less about lifecycle, memory leaks and crashes
-> MVVM gives more separation of concerns, less boilerplate and encourage the reactive approach
-> Provides clearer separation of the UI and application logic

Let's follow MVVM using Android architecture components.

**Comment by ritesh-singh** [comment]
First, this isn't a bug. You should have labeled it as an enhancement
Now, coming to the architecture level, you are right and your all points are valid regarding MVP and MVVM and make use of Architecture Components and everything.
