### ISSUE TITLE
SplashScreen remains open in background

### ISSUE THREAD

**Issue by ShivamArora** [UdacityAndroidDevScholarship/blood-donation#6]
Splash Screen remains open in background even after opening up the `HomeActivity`.

On pressing back from `HomeActivity` we still get the Splash Screen.

**Comment by sakchhams** [comment]
@ShivamArora I see two requests with the same title under your name. Please close one of them.

**Comment by ShivamArora** [comment]
@sakchhams Please take a look at it again.

The two issues are different.

One refers to the layout.
The other refers to the runtime functionality being wrong as it remains open in background.

Even the titles are different.

**Comment by sakchhams** [comment]
@ShivamArora Yes, I'm aware. They're very closely related and can be merged into one.

**Comment by ShivamArora** [comment]
@sakchhams Well for now, just merging the PR I've submitted will close both of them.

So there's no need to close one if the PR gets merged.

Take a look at the PR I've submitted solving these 2 issues.
