### ISSUE TITLE
Keyboard overlaps I AM IN button on login/signup page

### ISSUE THREAD

**Issue by shahidcodes** [UdacityAndroidDevScholarship/blood-donation#71]
### Environment
  * Version : 1.0.0
  * Device/Operating System : Android 8.0
  
### Bug:

  * What error did you encounter? Attaching screenshots or logs is always helpful. 
Keyboard overlaps `I AM IN` button. However UI should be moving up when keyboard gets in view.
[Screenshot](https://imgur.com/a/1UojdyW)
  * When does this occur?  
  While entering phone number on signup.

#### Steps to reproduce:

  1. Clear data if logged in
  2. Enter phone number on sign up screen
  3. Watch the keyboard covering the button
  ...
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
   The whole UI should move up show the `I AM IN` button

**Comment by tavishjain** [comment]
@shahidcodes we would have to change the layout file for that. Or have you planned something else?

**Comment by xsahil03x** [comment]
@shahidcodes (Resolved + PR sent) 😄

**Comment by ritesh-singh** [comment]
Great..!!

**Comment by shahidcodes** [comment]
It still covers up the button.
@xsahil03x could have used `adjustResize` instead of `adjustPan` in `android:windowSoftInputMode`. 
![ss](https://i.imgur.com/u6ZtQ12.jpg "ss")

**Comment by ritesh-singh** [comment]
@xsahil03x Had you checked, if the issue was resolved, before creating a PR for the same?

**Comment by xsahil03x** [comment]
@shahidcodes I checked everywhere and it's not possible to do this without resizing the whole layout.

**Comment by ritesh-singh** [comment]
@xsahil03x Yes, layout had to be changed.

**Comment by xsahil03x** [comment]
@ritesh-singh this is possible : https://camo.githubusercontent.com/3be6d81df51dbef73f8adba76111a00974117dc1/68747470733a2f2f692e696d6775722e636f6d2f734549356668392e6a7067

But in this the background is resized to create space for keyboard.

**Comment by ritesh-singh** [comment]
okay, @KamalMrock

**Comment by KamalMrock** [comment]
We will resolve this issue later.
Leave it for now.
