### ISSUE TITLE
! (Fixed length of Mobile Number)

### ISSUE THREAD

**Issue by xsahil03x** [UdacityAndroidDevScholarship/blood-donation#76]
### Bug: User is able to enter mobile number of any length at the Mobile Registration Activity
* eg : 8109341452225125245215

* The EditText should not accept any digit after the mobile number is completed
* i.e : 10 Digits (India)

**Comment by tavishjain** [comment]
Done and PR sent !!!

**Comment by tavishjain** [comment]
[https://github.com/UdacityAndroidDevScholarship/blood-donation/pull/81](url)

**Comment by tavishjain** [comment]
![whatsapp image 2018-04-28 at 1 33 04 am 1](https://user-images.githubusercontent.com/31106411/39382753-28ec0294-4a84-11e8-846d-a28b2a7c0660.jpeg)
![whatsapp image 2018-04-28 at 1 33 04 am](https://user-images.githubusercontent.com/31106411/39382754-2925ca24-4a84-11e8-8d24-4c12594f27a7.jpeg)

**Comment by tavishjain** [comment]
![whatsapp image 2018-04-28 at 11 05 38 am 1](https://user-images.githubusercontent.com/31106411/39392495-60c078f8-4ad4-11e8-8c1c-de7ba3a26ea8.jpeg)
![whatsapp image 2018-04-28 at 11 05 38 am](https://user-images.githubusercontent.com/31106411/39392496-60f37e38-4ad4-11e8-8c6d-13857dbb7d8b.jpeg)
![whatsapp image 2018-04-28 at 11 05 38 am 2](https://user-images.githubusercontent.com/31106411/39392497-6123f90a-4ad4-11e8-9b42-8235353b7cde.jpeg)


Took a pull and then took the screenshots.

**Comment by ritesh-singh** [comment]
#81

**Comment by ritesh-singh** [comment]
#81

**Comment by Hrishi1999** [comment]
Why not use Regex for constraints?

**Comment by KamalMrock** [comment]
@ritesh-singh Is this task completed?
