### ISSUE TITLE
Skip details profile screen for registered user

### ISSUE THREAD

**Issue by shahidcodes** [UdacityAndroidDevScholarship/blood-donation#77]
### Environment
  * Version : 1.0.0
  * Device/Operating System : Oreo 8.0
  
### Bug:

* What error did you encounter? Attaching screenshots or logs is always helpful.
  A registered user has to enter the profile details everytime.
* When does this occur? 
  When a registered user try to login.

#### Steps to reproduce:

  1. Register
  2. Clear data or uninstall
  3. Try to login then the profile screen will come.
  ...
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
    A registered user should be able to directly go to HomeActivity.

**Comment by vibhuti16** [comment]
Are you working on this. Want me to have a look?

**Comment by groverankush** [comment]
Hi. I have just completed this. About to merge the code.
