### ISSUE TITLE
Add "About" in app

### ISSUE THREAD

**Issue by KamalMrock** [UdacityAndroidDevScholarship/blood-donation#87]
This is free Blood Donation Mobile Application which helps needful patients to search for blood donors in their city or area and request for blood donation.Connecting blood donors and needy reduces time which increases the possibility of saving lives and also eliminates the shortage of blood. 

Please add this info in app About section.

![screenshot_20180501-183849](https://user-images.githubusercontent.com/25679263/39474051-aa05e8b6-4d6f-11e8-80c4-230dcfd0e3ac.png)

**Comment by GauravR31** [comment]
Can I take this up?

**Comment by KamalMrock** [comment]
@GauravR31 go ahead.

**Comment by KamalMrock** [comment]
And don't forget to add screen shot.

**Comment by GauravR31** [comment]
@KamalMrock Which screenshot?

**Comment by KamalMrock** [comment]
I mean when you are going to submit your PR than add screenshot of About.

**Comment by GauravR31** [comment]
Oh okay. Yeah I'll add the screenshot.
