### ISSUE TITLE
Change the location of "Current Location button" and "Request Button"

### ISSUE THREAD

**Issue by KamalMrock** [UdacityAndroidDevScholarship/blood-donation#88]
![screenshot_20180501-183859](https://user-images.githubusercontent.com/25679263/39474174-464b300a-4d70-11e8-9edd-ef2d2597c895.png)

Current Location and Request Button are very closed to right down corner and always covered by bottom sheet.
Put them little higher.Gap between both button is fine.Just move them little upward side.

**Comment by vibhuti16** [comment]
ill solve this

**Comment by KamalMrock** [comment]
@vibhuti16 go ahead.

**Comment by deepak-thakur** [comment]
i also want to do this. can i do this ?

**Comment by vibhuti16** [comment]
i have started working.

**Comment by KamalMrock** [comment]
@vibhuti16 any update?

**Comment by vibhuti16** [comment]
i cant get it go past entering phone number. i am looking into again today.

**Comment by Hrishi1999** [comment]
Check you firebase, check that of you have put SHA1 key, you have correct
google-services.json, and correct application ID.

**Comment by vibhuti16** [comment]
ok

**Comment by KamalMrock** [comment]
@vibhuti16 We are working in Develop branch ok!
