### ISSUE TITLE
App won't send OTP, stuck loader or no loader. 

### ISSUE THREAD

**Issue by Hrishi1999** [UdacityAndroidDevScholarship/blood-donation#92]
## Bug Report
I am trying to help contribute to this project since a few days, one thing stopping me is I can't get past the OTP screen

### Environment

  * Version : 7.0
  * Device/Operating System : Android
  
### Bug:

  * Nothing after entering phone number for OTP request.
 
#### Steps to reproduce:

  1. Start app
  2.Enter phone number
  3. Nothing happens, just stuck on loading screen. If I am debuggin on emulator, it will show a loader, on a real device, it won't show the loader. Logcat doesn't give any valuable information. 

I've enabled Authentication on Firebase dashboard. Checked everything.

**Comment by KamalMrock** [comment]
It is working.
