### ISSUE TITLE
No Close or Cancel button on Dialog

### ISSUE THREAD

**Issue by omi90** [UdacityAndroidDevScholarship/blood-donation#94]
### Description
 - If you click on + Button on main screen, a dialog comes for user to request blood or donate blood with some other details to fill up.
   But on the same dialog there is no provision to close it either with a close icon or a button, also back button also does not work to close the dialog. There is only one button Submit in the bottom. 

### How would the above feature be useful?
 - This would help user to close the dialog if he/she does not have anything to Submit and just checking the features of the app.

**Comment by KamalMrock** [comment]
@omi90 send screen shot.

**Comment by animeshroydev** [comment]
I would like to work on it...

**Comment by KamalMrock** [comment]
it is done @animeshroydev

**Comment by animeshroydev** [comment]
Is it merged @KamalMrock

**Comment by KamalMrock** [comment]
Not yet. 
You can work here #88 @animeshroydev

**Comment by KamalMrock** [comment]
Yes,Send your PR @animeshroydev 
and don't forget to add screen shot.

**Comment by groverankush** [comment]
Not required right now
